# Generated by Django 5.2.6 on 2025-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='employees',
            field=models.IntegerField(default=0),
        ),
    ]
