# Generated by Django 5.2.6 on 2025-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_plan_customers_plan_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
