# Generated by Django 5.2.6 on 2025-09-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='customers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='employees',
            field=models.IntegerField(null=True),
        ),
    ]
