# Generated by Django 5.2.6 on 2025-09-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_order_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.plan'),
        ),
    ]
