# Generated by Django 5.2.6 on 2025-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_order_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='workspace_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
