# Generated by Django 5.2.6 on 2025-09-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_order_owner_email_alter_order_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iqd_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
